# tack pins. edit by hand or with tack add / rm / alias
# nix reads pins.lock.json; this file drives tack update

[shorturls]
gh = "github:{path}"

[tack]
recomposable = true

[all_follow]
nixpkgs = ["nixpkgs-lib"]
nixpkgs-lib = "nixpkgs"

[inputs.nixpkgs]
# url = "gh:peachey2k2/nixpkgs-weekly"
url = "gh:NixOS/nixpkgs/nixos-unstable"
exclude_follow = ["nixpkgs"]

[inputs.tack]
url = "gh:manic-systems/tack"

[inputs.flake-parts]
url = "gh:hercules-ci/flake-parts"

[inputs.nur]
url = "gh:nix-community/NUR"

[inputs.zen-browser]
url = "gh:crashim03/zen-browser-flake"

[inputs.fenix]
url = "gh:nix-community/fenix/monthly"

[inputs._0fetch]
url = "gh:peachey2k2/0fetch"

[inputs.run0-sudo-shim]
url = "gh:lordgrimmauld/run0-sudo-shim"

[inputs.comfyui]
url = "gh:utensils/comfyui-nix"

[inputs.nilshell]
url = "path:../Projects/nilshell"

[inputs.reborder]
url = "path:../Projects/reborder"

[inputs.llm-agents]
url = "gh:numtide/llm-agents.nix"

# [inputs.beer]
# url = "git+https://git.notashelf.dev/notashelf/beer.git"

[inputs.blank]
url = "path:../Projects/blank"

# [inputs.kopuz]
# url = "github:Kopuz-org/kopuz"

[inputs.mesa]
url = "github:peachey2k2/nixpkgs-weekly?rev=4365e00c7cec13fb6d16b11638d9c76ae84f9bb7"

[inputs.autolith]
url = "gh:lambda-symbolics/autolith"

[inputs.disko]
url = "gh:nix-community/disko"

[inputs.website]
url = "gh:peachey2k2/peachey2k2.github.io"

[inputs.blight]
url = "git+ssh://git@github.com/cope-hq/blight"

