# tack pins. edit by hand or with tack add / rm / alias
# nix reads pins.lock.json; this file drives tack update

[shorturls]
gh = "github:{path}"

[tack]
recomposable = true

[all_follow]
nixpkgs = "nixpkgs"

[inputs.nixpkgs]
url = "gh:peachey2k2/nixpkgs-weekly"
exclude_follow = ["nixpkgs"]

[inputs.tack]
url = "gh:manic-systems/tack"

[inputs.flake-parts]
url = "gh:hercules-ci/flake-parts"

[inputs.nur]
url = "gh:nix-community/NUR"

[inputs.zen-browser]
url = "gh:crashim03/zen-browser-flake"

[inputs.fenix]
url = "gh:nix-community/fenix/monthly"

[inputs._0fetch]
url = "gh:peachey2k2/0fetch"

[inputs.run0-sudo-shim]
url = "gh:lordgrimmauld/run0-sudo-shim"

[inputs.comfyui]
url = "gh:utensils/comfyui-nix"

[inputs.nilshell]
url = "path:../Projects/nilshell"

[inputs.reborder]
url = "path:../Projects/reborder"

[inputs.pi-alternate]
url = "gh:cope-hq/pi-alternate"
type = "fetch"

[inputs.beer]
# url = "git+https://git.notashelf.dev/notashelf/beer.git"
url = "https://git.notashelf.dev/notashelf/beer/archive/f52a4011ab82c3808b303c3aa38bead11d5c6d8f.tar.gz"

